### ISSUE TITLE
Question about the Movement function / Frage zur Movement Funktion

### ISSUE THREAD

**Issue by zengtronic** [SensorsIot/Self-Balancing-Robot#1]
Moin,
eine Frage zur movement() Funktion:
Wie genau Funktioniert die Berechnung der aktuellen Geschwindigkeit? Verstehe die Zeile 632 mit der Winkelgeschwindigkeit nicht so genau, also weshalb man die Winkelveränderung noch mit 90 multipliziert.
In ihrem Youtube-Video wird darauf leider nicht eingegangen.
-----------------------------------------------------------------------
Hello,
a question about the movement() function:
How exactly does the calculation of the current speed work? I don't quite understand line 632 with the angular velocity, which is why the change in angle is multiplied by 90.
Unfortunately, their YouTube video does not address this.

**Comment by SensorsIot** [comment]
Das weiss ich leider auch nicht mehr so genau (das Video ist schon alt) und ich habe Teile des Codes aus dem B-Robot Projekt übernommen (Link in der Video Beschreibung).
